# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hpricot_scrub}
  s.version = "0.3.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["UnderpantsGnome (Michael Moen)", "minaguib (Mina Naguib)"]
  s.date = %q{2010-01-25}
  s.description = %q{Scrub HTML with Hpricot like you would with perl HTML:Scrubber}
  s.email = %q{michael@underpantsgnome.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.txt",
     "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "examples/config.yml",
     "examples/old_config.yml",
     "hpricot_scrub.gemspec",
     "lib/hpricot_scrub.rb",
     "lib/hpricot_scrub/hpricot_scrub.rb",
     "lib/hpricot_scrub/version.rb",
     "setup.rb",
     "test/hpricot_scrub_test.rb",
     "test/old_hpricot_scrub_test.rb",
     "test/scrubber_data.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/UnderpantsGnome/hpricot_scrub}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Scrub HTML with Hpricot}
  s.test_files = [
    "test/hpricot_scrub_test.rb",
     "test/old_hpricot_scrub_test.rb",
     "test/scrubber_data.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8.1"])
    else
      s.add_dependency(%q<hpricot>, [">= 0.8.1"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0.8.1"])
  end
end

