---
  :allow_tags: # let these tags stay, but will strip attributes
    - 'html'
    - 'head'
    - 'body'
    - 'b'
    - 'blockquote'
    - 'br'
    - 'div'
    - 'h1'
    - 'h2'
    - 'h3'
    - 'h4'
    - 'h5'
    - 'h6'
    - 'hr'
    - 'i'
    - 'em'
    - 'img'
    - 'li'
    - 'ol'
    - 'p'
    - 'pre'
    - 'small'
    - 'span'
    - 'span'
    - 'strike'
    - 'strong'
    - 'sub'
    - 'sup'
    - 'table'
    - 'tbody'
    - 'td'
    - 'tfoot'
    - 'thead'
    - 'tr'
    - 'u'
    - 'ul'

  :remove_tags: # completely removes everything between open and close tag
    - 'form'
    - 'script'
    
  :allow_attributes: # let these attributes stay, strip all others
    - 'src'
    - 'font'
    - 'alt'
    - 'style'
    - 'align'
